// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { GamerProfileWithComments$Type } from "./GamerProfileWithComments";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["GamerProfileWithComments"]: GamerProfileWithComments$Type;
    ["contracts/ProfileWithCmt.sol:GamerProfileWithComments"]: GamerProfileWithComments$Type;
  }

  interface ContractTypesMap {
    ["GamerProfileWithComments"]: GetContractReturnType<GamerProfileWithComments$Type["abi"]>;
    ["contracts/ProfileWithCmt.sol:GamerProfileWithComments"]: GetContractReturnType<GamerProfileWithComments$Type["abi"]>;
  }
}
